daysUntilClose: false
staleLabel: stale

issues:
  daysUntilStale: 60
  markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be now be reviewed manually. Thank you
    for your contributions.

pulls:
   daysUntilStale: 7
   markComment: >
     This pull request has been automatically marked as stale because it has not had
     recent activity. It will be now be reviewed manually. Thank you
     for your contributions.

