package org.kiwix.kiwixmobile.wifi_hotspot;

public enum WIFI_AP_STATE_ENUMS {
  WIFI_AP_STATE_DISABLING, WIFI_AP_STATE_DISABLED, WIFI_AP_STATE_ENABLING, WIFI_AP_STATE_ENABLED, WIFI_AP_STATE_FAILED
}
