/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIKiwix */

#ifndef _Included_JNIKiwix
#define _Included_JNIKiwix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIKiwix
 * Method:    nativeLoadZIM
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_JNIKiwix_nativeLoadZIM
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JNIKiwix
 * Method:    nativeGetContent
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIKiwix_nativeGetContent
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
