import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
  const val de_fayard_buildsrcversions_gradle_plugin: String =
      "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
      Versions.de_fayard_buildsrcversions_gradle_plugin

  const val com_github_triplet_play_gradle_plugin: String =
      "com.github.triplet.play:com.github.triplet.play.gradle.plugin:" +
      Versions.com_github_triplet_play_gradle_plugin

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val android_arch_lifecycle_extensions: String = "android.arch.lifecycle:extensions:" +
      Versions.android_arch_lifecycle_extensions

  /**
   * https://developer.android.com/studio
   */
  const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
      Versions.com_android_tools_build_gradle

  const val androidx_multidex_multidex: String = "androidx.multidex:multidex:" +
      Versions.androidx_multidex_multidex

  /**
   * https://github.com/JakeWharton/butterknife/
   */
  const val butterknife_gradle_plugin: String = "com.jakewharton:butterknife-gradle-plugin:" +
      Versions.butterknife_gradle_plugin

  const val multidex_instrumentation: String = "androidx.multidex:multidex-instrumentation:" +
      Versions.multidex_instrumentation

  /**
   * https://developer.android.com/testing
   */
  const val espresso_contrib: String = "androidx.test.espresso:espresso-contrib:" +
      Versions.androidx_test_espresso

  /**
   * https://developer.android.com/testing
   */
  const val espresso_core: String = "androidx.test.espresso:espresso-core:" +
      Versions.androidx_test_espresso

  /**
   * https://developer.android.com/testing
   */
  const val espresso_intents: String = "androidx.test.espresso:espresso-intents:" +
      Versions.androidx_test_espresso

  /**
   * https://developer.android.com/testing
   */
  const val espresso_web: String = "androidx.test.espresso:espresso-web:" +
      Versions.androidx_test_espresso

  /**
   * https://github.com/square/retrofit/
   */
  const val adapter_rxjava2: String = "com.squareup.retrofit2:adapter-rxjava2:" +
      Versions.com_squareup_retrofit2

  /**
   * https://github.com/square/retrofit/
   */
  const val converter_simplexml: String = "com.squareup.retrofit2:converter-simplexml:" +
      Versions.com_squareup_retrofit2

  /**
   * https://github.com/square/retrofit/
   */
  const val retrofit: String = "com.squareup.retrofit2:retrofit:" + Versions.com_squareup_retrofit2

  const val play_services_location: String = "com.google.android.gms:play-services-location:" +
      Versions.play_services_location

  /**
   * https://developer.android.com/testing
   */
  const val androidx_test_runner: String = "androidx.test:runner:" + Versions.androidx_test_runner

  /**
   * https://github.com/JakeWharton/butterknife/
   */
  const val butterknife_compiler: String = "com.jakewharton:butterknife-compiler:" +
      Versions.butterknife_compiler

  /**
   * http://jcp.org/en/jsr/detail?id=250
   */
  const val javax_annotation_api: String = "javax.annotation:javax.annotation-api:" +
      Versions.javax_annotation_api

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions: String = "org.jetbrains.kotlin:kotlin-android-extensions:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions_runtime: String =
      "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_annotation_processing_gradle: String =
      "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_stdlib_jdk7: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://developer.android.com/testing
   */
  const val androidx_test_rules: String = "androidx.test:rules:" + Versions.androidx_test_rules

  /**
   * https://github.com/square/okhttp
   */
  const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
      Versions.logging_interceptor

  /**
   * https://developer.android.com/testing
   */
  const val androidx_test_core: String = "androidx.test:core:" + Versions.androidx_test_core

  /**
   * http://hc.apache.org/httpcomponents-client/
   */
  const val httpclient_android: String = "org.apache.httpcomponents:httpclient-android:" +
      Versions.httpclient_android

  const val ink_page_indicator: String = "com.pacioianu.david:ink-page-indicator:" +
      Versions.ink_page_indicator

  /**
   * http://github.com/square/leakcanary/
   */
  const val leakcanary_android: String = "com.squareup.leakcanary:leakcanary-android:" +
      Versions.leakcanary_android

  /**
   * https://github.com/google/dagger
   */
  const val dagger: String = "com.google.dagger:dagger:" + Versions.com_google_dagger

  /**
   * https://github.com/google/dagger
   */
  const val dagger_android: String = "com.google.dagger:dagger-android:" +
      Versions.com_google_dagger

  /**
   * https://github.com/google/dagger
   */
  const val dagger_android_processor: String = "com.google.dagger:dagger-android-processor:" +
      Versions.com_google_dagger

  /**
   * https://github.com/google/dagger
   */
  const val dagger_compiler: String = "com.google.dagger:dagger-compiler:" +
      Versions.com_google_dagger

  /**
   * https://github.com/yahoo/squidb
   */
  const val squidb: String = "com.yahoo.squidb:squidb:" + Versions.com_yahoo_squidb

  /**
   * https://github.com/yahoo/squidb
   */
  const val squidb_annotations: String = "com.yahoo.squidb:squidb-annotations:" +
      Versions.com_yahoo_squidb

  /**
   * https://github.com/yahoo/squidb
   */
  const val squidb_processor: String = "com.yahoo.squidb:squidb-processor:" +
      Versions.com_yahoo_squidb

  /**
   * http://tools.android.com
   */
  const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
      Versions.constraintlayout

  /**
   * https://github.com/mockito/mockito
   */
  const val mockito_android: String = "org.mockito:mockito-android:" + Versions.mockito_android

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val collection_ktx: String = "androidx.collection:collection-ktx:" + Versions.collection_ktx

  const val jacoco_android: String = "com.dicedmelon.gradle:jacoco-android:" +
      Versions.jacoco_android

  /**
   * https://junit.org/junit5/
   */
  const val junit_jupiter: String = "org.junit.jupiter:junit-jupiter:" + Versions.junit_jupiter

  const val ktlint_gradle: String = "org.jlleitschuh.gradle:ktlint-gradle:" + Versions.ktlint_gradle

  /**
   * https://github.com/square/okhttp
   */
  const val mockwebserver: String = "com.squareup.okhttp3:mockwebserver:" + Versions.mockwebserver

  /**
   * https://github.com/bitbar/testdroid-api
   */
  const val testdroid_api: String = "com.testdroid:testdroid-api:" + Versions.testdroid_api

  const val xfetch2okhttp: String = "androidx.tonyodev.fetch2okhttp:xfetch2okhttp:" +
      Versions.xfetch2okhttp

  /**
   * http://assertj.org
   */
  const val assertj_core: String = "org.assertj:assertj-core:" + Versions.assertj_core

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val core_testing: String = "androidx.arch.core:core-testing:" + Versions.core_testing

  /**
   * https://developer.android.com/jetpack/androidx
   */
  const val fragment_ktx: String = "androidx.fragment:fragment-ktx:" + Versions.fragment_ktx

  /**
   * http://objectbox.io
   */
  const val objectbox_android: String = "io.objectbox:objectbox-android:" + Versions.io_objectbox

  /**
   * https://objectbox.io
   */
  const val objectbox_gradle_plugin: String = "io.objectbox:objectbox-gradle-plugin:" +
      Versions.io_objectbox

  /**
   * http://objectbox.io
   */
  const val objectbox_kotlin: String = "io.objectbox:objectbox-kotlin:" + Versions.io_objectbox

  /**
   * https://objectbox.io
   */
  const val objectbox_processor: String = "io.objectbox:objectbox-processor:" +
      Versions.io_objectbox

  /**
   * http://objectbox.io
   */
  const val objectbox_rxjava: String = "io.objectbox:objectbox-rxjava:" + Versions.io_objectbox

  /**
   * http://objectbox.io
   */
  const val objectbox_windows: String = "io.objectbox:objectbox-windows:" + Versions.io_objectbox

  /**
   * https://developer.android.com/testing
   */
  const val orchestrator: String = "androidx.test:orchestrator:" + Versions.orchestrator

  /**
   * https://github.com/JakeWharton/butterknife/
   */
  const val butterknife: String = "com.jakewharton:butterknife:" + Versions.butterknife

  /**
   * https://developer.android.com/studio
   */
  const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

  /**
   * https://github.com/jraska/livedata-testing
   */
  const val testing_ktx: String = "com.jraska.livedata:testing-ktx:" + Versions.testing_ktx

  /**
   * https://github.com/JakeWharton/ThreeTenABP/
   */
  const val threetenabp: String = "com.jakewharton.threetenabp:threetenabp:" + Versions.threetenabp

  /**
   * https://developer.android.com/testing
   */
  const val uiautomator: String = "androidx.test.uiautomator:uiautomator:" + Versions.uiautomator

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val androidx_annotation: String = "androidx.annotation:annotation:" + Versions.annotation

  /**
   * http://jacoco.org
   */
  const val org_jacoco_agent: String = "org.jacoco:org.jacoco.agent:" + Versions.org_jacoco

  /**
   * http://jacoco.org
   */
  const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:" + Versions.org_jacoco

  /**
   * http://simple.sourceforge.net
   */
  const val simple_xml: String = "org.simpleframework:simple-xml:" + Versions.simple_xml

  /**
   * https://developer.android.com/jetpack/androidx
   */
  const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

  /**
   * https://github.com/ReactiveX/RxAndroid
   */
  const val rxandroid: String = "io.reactivex.rxjava2:rxandroid:" + Versions.rxandroid

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val cardview: String = "androidx.cardview:cardview:" + Versions.cardview

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

  /**
   * http://mockk.io
   */
  const val mockk: String = "io.mockk:mockk:" + Versions.io_mockk

  /**
   * http://mockk.io
   */
  const val mockk_android: String = "io.mockk:mockk-android:" + Versions.io_mockk

  /**
   * https://github.com/kiwix/kiwix-lib
   */
  const val kiwixlib: String = "org.kiwix.kiwixlib:kiwixlib:" + Versions.kiwixlib

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val material: String = "com.google.android.material:material:" + Versions.material

  const val barista: String = "com.schibsted.spain:barista:" + Versions.barista

  const val xfetch2: String = "androidx.tonyodev.fetch2:xfetch2:" + Versions.xfetch2

  /**
   * http://findbugs.sourceforge.net/
   */
  const val jsr305: String = "com.google.code.findbugs:jsr305:" + Versions.jsr305

  /**
   * https://github.com/square/okhttp
   */
  const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.okhttp

  /**
   * https://github.com/ReactiveX/RxJava
   */
  const val rxjava: String = "io.reactivex.rxjava2:rxjava:" + Versions.rxjava

  /**
   * https://developer.android.com/studio
   */
  const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

  /**
   * https://developer.android.com/testing
   */
  const val junit: String = "androidx.test.ext:junit:" + Versions.junit
}
