name: Publish fdroid nightly build

# This workflow is triggered on a schedule or when specific tags are pushed.
# It runs every Monday at 12:00 UTC and also when the 'fdroid_nightly' tag is pushed.
on:
  push:
    tags:
      - 'fdroid_nightly' # fdroid_nightly Tag
  schedule:
    - cron: '0 12 * * 1'  # Runs every Monday at 12:00

jobs:
  nightly:
    name: Publish nightly build
    runs-on: ubuntu-22.04
    environment: nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build
        run: |
          ./gradlew assembleDebug

      - name: fdroid nightly
        run: |
          sudo add-apt-repository ppa:fdroid/fdroidserver
          sudo apt-get update
          sudo apt-get install apksigner fdroidserver --no-install-recommends
          export DEBUG_KEYSTORE=$\{\{ secrets.DEBUG_KEYSTORE \}\}
          fdroid nightly --archive-older 10
